import type { ActivityEvent } from "@/domains/activity/store/activity.types";
import type { CalendarEvent } from "@/domains/calendar/store/calendar.types";
import type { Client, ClientTask, ClientUnitLink } from "@/domains/clients/store/clients.types";
import type { AgentChatMessage, AgentThread } from "@/domains/agents/api/chat";
import type { PartnerCatalogApp, PartnerConnection } from "@/domains/integrations/store/integrations.types";
import type { Project } from "@/domains/projects/store/projects.types";
import type { PropertyUnit } from "@/domains/properties/store/properties.types";
import { appConfig } from "@/app-config";

const now = Date.now();
const day = 24 * 60 * 60 * 1000;

export const demoProjects: Project[] = [
  {
    id: "prj-1",
    name: "Northstar Launch",
    reference: "PRJ-001",
    developer: "Acme Studio",
    city: "Riyadh",
    area: "Operations",
    type: "Program",
    unitTypes: ["Workflow", "Reporting"],
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=800&auto=format&fit=crop",
    coverImageUrl: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=800&auto=format&fit=crop",
    status: "approved",
    visibility: "public",
    syncState: "synced",
    units: 42,
    priceRange: "Ready",
    averagePrice: "Ready",
    updated: "2h ago",
    updatedAt: now - 2 * 60 * 60 * 1000,
    createdAt: now - 12 * day,
    description: "A polished example project for dashboard cards, detail views, and related records.",
  },
  {
    id: "prj-2",
    name: "Atlas Reporting",
    reference: "PRJ-002",
    developer: "Internal Team",
    city: "Jeddah",
    area: "Analytics",
    type: "Dashboard",
    unitTypes: ["Table", "Chart", "Export"],
    image: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?q=80&w=800&auto=format&fit=crop",
    coverImageUrl: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?q=80&w=800&auto=format&fit=crop",
    status: "pending",
    visibility: "private",
    syncState: "blocked",
    units: 18,
    priceRange: "Review",
    averagePrice: "Review",
    updated: "1d ago",
    updatedAt: now - day,
    createdAt: now - 9 * day,
    description: "A pending project used to demonstrate warning states and review workflows.",
  },
  {
    id: "prj-3",
    name: "Beacon Onboarding",
    reference: "PRJ-003",
    developer: "Chats Team",
    city: "Dammam",
    area: "Customer Success",
    type: "Workflow",
    unitTypes: ["Guide"],
    image: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?q=80&w=800&auto=format&fit=crop",
    coverImageUrl: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?q=80&w=800&auto=format&fit=crop",
    status: "draft",
    visibility: "private",
    syncState: "draft",
    units: 24,
    priceRange: "Draft",
    averagePrice: "Draft",
    updated: "3d ago",
    updatedAt: now - 3 * day,
    createdAt: now - 6 * day,
    description: "A draft project that keeps empty, draft, and edit states visible in Chats UI.",
  },
];

export const demoProperties: PropertyUnit[] = [
  {
    id: "unt-1",
    title: "Executive Overview",
    reference: "A-101",
    projectId: "prj-1",
    project: "Northstar Launch",
    city: "Riyadh",
    type: "Dashboard",
    image: "https://images.unsplash.com/photo-1551434678-e076c223a692?q=80&w=800&auto=format&fit=crop",
    coverImageUrl: "https://images.unsplash.com/photo-1551434678-e076c223a692?q=80&w=800&auto=format&fit=crop",
    status: "available",
    visibility: "public",
    purpose: "sale",
    price: "Ready",
    area: "120 m2",
    bedrooms: 2,
    bathrooms: 2,
    updated: "2h ago",
    updatedAt: now - 2 * 60 * 60 * 1000,
    createdAt: now - 10 * day,
    description: "A reusable overview record for detail pages, gallery blocks, and linked contacts.",
  },
  {
    id: "unt-2",
    title: "Metrics Board",
    reference: "B-301",
    projectId: "prj-1",
    project: "Northstar Launch",
    city: "Jeddah",
    type: "Analytics",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=800&auto=format&fit=crop",
    coverImageUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=800&auto=format&fit=crop",
    status: "pending",
    visibility: "private",
    purpose: "rent",
    price: "Review",
    area: "280 m2",
    bedrooms: 4,
    bathrooms: 4,
    updated: "1d ago",
    updatedAt: now - day,
    createdAt: now - 8 * day,
    description: "A pending record for showing status filters, table rows, and form defaults.",
  },
  {
    id: "unt-3",
    title: "Workflow Detail",
    reference: "V-07",
    projectId: "prj-3",
    project: "Beacon Onboarding",
    city: "Dammam",
    type: "Workflow",
    image: "https://images.unsplash.com/photo-1552664730-d307ca884978?q=80&w=800&auto=format&fit=crop",
    coverImageUrl: "https://images.unsplash.com/photo-1552664730-d307ca884978?q=80&w=800&auto=format&fit=crop",
    status: "draft",
    visibility: "private",
    purpose: "sale",
    price: "Draft",
    area: "450 m2",
    bedrooms: 5,
    bathrooms: 6,
    updated: "3d ago",
    updatedAt: now - 3 * day,
    createdAt: now - 5 * day,
    description: "A draft detail item used by upload, empty media, and delete confirmation states.",
  },
];

export const demoClients: Client[] = [
  {
    id: "cl-1",
    organizationId: appConfig.demoOrganizationId,
    name: "Jordan Lee",
    type: "Buyer",
    contact: "jordan@example.com",
    phone: "+1 555 0101",
    age: 34,
    nationality: "US",
    generation: "Millennial",
    budget: "High priority",
    propertyInterest: "Executive Overview",
    status: "active",
    visibility: "private",
    added: "May 1, 2026",
    pipelineStage: "qualified",
    pipelineOrder: 100,
    priority: "high",
    lastContact: "Today",
    nextAction: "Send summary",
    nextActionDate: "May 18, 2026",
    appointmentTime: "10:30",
    syncState: "eligible",
    createdAt: now - 7 * day,
    updatedAt: now - 60 * 60 * 1000,
  },
  {
    id: "cl-2",
    organizationId: appConfig.demoOrganizationId,
    name: "Sam Rivera",
    type: "Tenant",
    contact: "sam@example.com",
    phone: "+1 555 0102",
    age: 29,
    nationality: "US",
    generation: "Millennial",
    budget: "Medium",
    propertyInterest: "Metrics Board",
    status: "active",
    visibility: "private",
    added: "May 2, 2026",
    pipelineStage: "new",
    pipelineOrder: 100,
    priority: "normal",
    lastContact: "Yesterday",
    nextAction: "Confirm kickoff",
    nextActionDate: "May 19, 2026",
    appointmentTime: "13:00",
    syncState: "draft",
    createdAt: now - 6 * day,
    updatedAt: now - 18 * 60 * 60 * 1000,
  },
  {
    id: "cl-3",
    organizationId: appConfig.demoOrganizationId,
    name: "Capital Ventures",
    type: "Investor",
    contact: "ops@example.com",
    phone: "+1 555 0103",
    age: 42,
    nationality: "US",
    generation: "Gen X",
    budget: "Enterprise",
    propertyInterest: "Atlas Reporting",
    status: "active",
    visibility: "public",
    added: "Apr 28, 2026",
    pipelineStage: "negotiation",
    pipelineOrder: 100,
    priority: "urgent",
    lastContact: "May 16",
    nextAction: "Share report",
    nextActionDate: "May 20, 2026",
    appointmentTime: "09:15",
    syncState: "synced",
    createdAt: now - 14 * day,
    updatedAt: now - 2 * day,
  },
  {
    id: "cl-4",
    organizationId: appConfig.demoOrganizationId,
    name: "Taylor Chen",
    type: "Broker",
    contact: "taylor@example.com",
    phone: "+1 555 0104",
    age: 39,
    nationality: "US",
    generation: "Gen X",
    budget: "Partner pipeline",
    propertyInterest: "Workflow Detail",
    status: "inactive",
    visibility: "private",
    added: "Apr 15, 2026",
    pipelineStage: "viewing",
    pipelineOrder: 100,
    priority: "normal",
    lastContact: "Apr 30",
    nextAction: "Review agreement",
    nextActionDate: "May 21, 2026",
    appointmentTime: "15:30",
    syncState: "blocked",
    issue: "Agreement needs review.",
    createdAt: now - 18 * day,
    updatedAt: now - 4 * day,
  },
];

export const demoClientUnitLinks: ClientUnitLink[] = [
  { _id: "link-1", id: "link-1", clientId: "cl-1", propertyId: "unt-1", status: "shortlisted", notes: "Strong match for current priority." } as ClientUnitLink,
  { _id: "link-2", id: "link-2", clientId: "cl-3", propertyId: "unt-2", status: "offer", notes: "Waiting for approval." } as ClientUnitLink,
  { _id: "link-3", id: "link-3", clientId: "cl-4", propertyId: "unt-3", status: "viewing", notes: "Demo relationship for detail pages." } as ClientUnitLink,
];

export const demoClientTasks: ClientTask[] = [
  { id: "task-1", clientId: "cl-1", title: "Send dashboard summary", status: "open", priority: "high", dueAt: now + day, notes: "Use this to test task cards." },
  { id: "task-2", clientId: "cl-2", title: "Confirm onboarding call", status: "open", priority: "normal", dueAt: now + 2 * day },
  { id: "task-3", clientId: "cl-3", title: "Prepare metrics export", status: "done", priority: "urgent", completedAt: now - day },
];

export const demoCalendarEvents: CalendarEvent[] = [
  { id: "cal-1", organizationId: appConfig.demoOrganizationId, title: "Dashboard review", owner: "Jordan Lee", date: "2026-05-18", time: "10:30", type: "meeting", status: "confirmed", clientId: "cl-1", propertyId: "unt-1", unitId: "unt-1", clientName: "Jordan Lee", unitTitle: "Executive Overview", startAt: now + 2 * 60 * 60 * 1000, endAt: now + 3 * 60 * 60 * 1000, location: "Demo room" },
  { id: "cal-2", organizationId: appConfig.demoOrganizationId, title: "Metrics walkthrough", owner: "Capital Ventures", date: "2026-05-19", time: "13:00", type: "audit", status: "pending", clientId: "cl-3", propertyId: "unt-2", clientName: "Capital Ventures", unitTitle: "Metrics Board", startAt: now + day, endAt: now + day + 60 * 60 * 1000 },
  { id: "cal-3", organizationId: appConfig.demoOrganizationId, title: "Onboarding sync", owner: "Sam Rivera", date: "2026-05-20", time: "15:15", type: "follow-up", status: "draft", clientId: "cl-2", clientName: "Sam Rivera", startAt: now + 2 * day, endAt: now + 2 * day + 45 * 60 * 1000 },
];

export const demoActivityEvents: ActivityEvent[] = [
  { id: "act-1", actor: "Alex Morgan", action: "approved", target: "Northstar Launch", status: "approved", date: "2m ago" },
  { id: "act-2", actor: "Demo Service", action: "updated", target: "Metrics Board", status: "pending", date: "1h ago" },
  { id: "act-3", actor: "Chats Owner", action: "created draft", target: "Workflow Detail", status: "draft", date: "3h ago" },
  { id: "act-4", actor: "Local Mock", action: "requested review", target: "Capital Ventures", status: "pending", date: "1d ago" },
];

export const demoAgentThreads: AgentThread[] = [
  { id: "thread-1", organizationId: appConfig.demoOrganizationId, title: "Dashboard summary", createdByUserId: "demo-user", createdAt: now - day, updatedAt: now - 60 * 60 * 1000, lastMessageAt: now - 60 * 60 * 1000 },
  { id: "thread-2", organizationId: appConfig.demoOrganizationId, title: "Pipeline cleanup", createdByUserId: "demo-user", createdAt: now - 2 * day, updatedAt: now - day, lastMessageAt: now - day },
];

export const demoAgentMessages: AgentChatMessage[] = [
  { id: "msg-1", role: "assistant", content: "This is a local demo assistant. Replace `src/domains/agents/api/chat.ts` with your real runtime when you add backend services.", createdAt: now - 60 * 60 * 1000 },
];

export const demoPartnerApps: PartnerCatalogApp[] = [
  { id: "app-1", partnersClientId: "crm-demo", name: "CRM Sync", publisherName: "Demo Apps", description: "Example module card for app and integration layouts.", homepageUrl: "https://example.com", allowedScopes: ["clients:read", "clients:write"], redirectUris: ["https://example.com/oauth"], status: "approved", updatedAt: now - day },
  { id: "app-2", partnersClientId: "reports-demo", name: "Reports Hub", publisherName: "Demo Apps", description: "A second module to keep list and empty states realistic.", homepageUrl: "https://example.com", allowedScopes: ["reports:read"], redirectUris: ["https://example.com/oauth"], status: "approved", updatedAt: now - 2 * day },
];

export const demoPartnerConnections: PartnerConnection[] = [
  { id: "conn-1", organizationId: appConfig.demoOrganizationId, partnersAppId: "app-1", partnersClientId: "crm-demo", status: "active", effectiveStatus: "active", scopes: ["clients:read"], updatedAt: now - 3 * 60 * 60 * 1000, partnerApp: demoPartnerApps[0] },
];
